config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  root "home#index"
  resources :home, only: [:index] # ホーム画面（各ページへのリンクが存在）
  resources :emboss, only: [:index, :create] # 勤怠打刻
  resources :mytimes, only: [:index, :show] # 自分の勤怠を確認
  resources :fix_time, only: [:index, :edit, :update] # 勤怠修正
  resources :change_auth, only: [:index, :update] # 権限設定
end

app/controllers/mytimes_controller.rb
class MytimesController < ApplicationController
  # 自分の出勤確認に関するコントローラー

  before_action :move_to_Log_in

  def index 
    year = Time.current.strftime("%Y").to_i # 現在の年
    month = Time.current.strftime("%-m").to_i # 現在の月
    user_id = current_user.id
    @attendances = Attendance.get_mytimes(year, month, user_id)
    @year = year
    @month = month
    render :show
  end

  def show
    year = params_year # ユーザーが設定した年
    month = params_month # ユーザーが設定した月
    user_id = current_user.id
    @attendances = Attendance.get_mytimes(year, month, user_id)
    @year = year
    @month = month
  end

  private
  def params_year
    params.require(:date)[:year].to_i
  end

  def params_month
    params.require(:date)[:month].to_i
  end
end

app/views/mytimes/_header_form_date_contents.html.haml
.select-box
  = select_tag 'date[year]', options_for_select([Time.current.year, ago_year(1), ago_year(2), ago_year(3), ago_year(4), ago_year(5), ago_year(6), ago_year(7), ago_year(8), ago_year(9)], selected: @year)
  .icon-chevron-down
    = fa_icon("chevron-down") 
  .select-box-character
    年
.select-box
  = select_tag 'date[month]', options_for_select(["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"], selected: @month)
  .icon-chevron-down
    = fa_icon("chevron-down") 
  .select-box-character
    月

app/views/mytimes/_title_header.html.haml
.fix-mytimes-show-header
  .title
    %h1 Time-Card
  .page-title
    = page_title
  .btn-area
    = link_to home_index_path, class: "common-header__btn-area__btn btn-color-white" do
      home
    = link_to destroy_user_session_path, method: :delete, class: "common-header__btn-area__btn btn-color-blue" do
      logout

app/views/mytimes/_tr_title.html.haml
%tr
  %th= "#{@month}月"
  %th 勤務
  %th 出勤時間
  %th 退勤時間
  %th 勤務時間

app/views/mytimes/show.html.haml
.fix-wrapper
  .mytimes-show-wrapper
    = render partial: 'mytimes/title_header', locals: { page_title: "自分の勤怠確認" }
    .mytimes-show-wrapper__header
      = form_with(url: mytime_path(current_user.id), method: :get, local: true, class: "date-form-area") do |f|
        .header-form
          .header-form__name
            = current_user.name
          .header-form__date
            = render 'mytimes/header_form_date_contents'
            .date-send-btn
              = f.submit "確認", class: "send-btn"

    .mytimes-show-wrapper__contents
      .mytimes-show-wrapper__contents__table.mytimes-show-wrapper__contents__table__add-class
        %table
          = render 'mytimes/tr_title'
          - @attendances.each do |attendance|
            -if attendance[0] == "holiday"
              %tr
                %td= set_date(attendance[1])
                %td 休
                %td
                %td
                %td
            -else
              %tr
                %td= set_date(attendance.going_to_work)
                %td
                %td= set_time(attendance.going_to_work)
                %td= set_time(attendance.leave_work)
                %td= set_working_hours(attendance.going_to_work, attendance.leave_work)

  .fix-wrapper__footer