config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  root "home#index"
  resources :home, only: [:index] # ホーム画面（各ページへのリンクが存在）
  resources :emboss, only: [:index, :create] # 勤怠打刻
  resources :mytimes, only: [:index, :show] # 自分の勤怠を確認
  resources :fix_time, only: [:index, :edit, :update] # 勤怠修正
  resources :change_auth, only: [:index, :update] # 権限設定
end

app/controllers/fix_time_controller.rb
class FixTimeController < ApplicationController
  # 勤怠編集に関するコントローラー

  before_action :move_to_Log_in
  before_action :check_authority_Stop_other_than_admin

  def index
    @users = User.all
    @month = Time.current.strftime("%-m").to_i
  end

  def edit # 勤怠編集画面へ
    year = year_params
    month = month_params
    user_id = user_id_params
    @attendances = Attendance.get_member_attendances(year, month, user_id)
    @user = User.find(user_id)
    @year = year
    @month = month
  end

  def update # 勤怠編集処理
    year = params.require(:year).to_i
    month = params.require(:month).to_i
    user = User.find(params.require(:user_id).to_i)
    my_id = current_user.id
    Attendance.create_new_attendances(new_Attendances_params, year, month, user, my_id) if new_Attendances_params # 勤怠レコードを新しく作る
    Attendance.update_edit_attendances(params, year, month, user, my_id) if edit_Attendances_params # すでに存在する勤怠レコードを修正する

    @attendances = Attendance.get_member_attendances(year, month, user.id)
    @user = user
    @year = year
    @month = month
    render :edit
  end

  private
  def year_params
    params.require(:date)[:year].to_i
  end

  def month_params
    params.require(:date)[:month].to_i
  end

  def user_id_params
    params.require(:user)[:name_select].to_i
  end

  def new_Attendances_params
    if params[:newAttendances]
      params.require(:newAttendances)
    else
      return false
    end
  end

  def edit_Attendances_params
    if params[:editAttendances]
      params.require(:editAttendances)
    else
      return false
    end
  end
end

app/views/fix_time/edit.html.haml
.fix-wrapper
  .mytimes-show-wrapper
    = render partial: 'mytimes/title_header', locals: { page_title: "勤怠確認と修正" }

    .mytimes-show-wrapper__header
      = form_with(url: edit_fix_time_path(@user.id), method: :get, local: true, name: "aa", class: "date-form-area", id: "date-and-name-form-area") do |f|
        .header-form
          .header-form__name
            = collection_select(:user, :name_select, User.all, :id, :name, {selected: @user.id}, {class: "fix-time-edit_select"})
            .icon-chevron-down
              = fa_icon("chevron-down")
          .header-form__date
            .select-box
              = select_tag 'date[year]', options_for_select([Time.current.year, ago_year(1), ago_year(2), ago_year(3), ago_year(4), ago_year(5), ago_year(6), ago_year(7), ago_year(8), ago_year(9)], selected: @year), {class: "fix-time-edit_select"}
              .icon-chevron-down
                = fa_icon("chevron-down")
              .select-box-character
                年
            .select-box
              = select_tag 'date[month]', options_for_select(["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"], selected: @month), {class: "fix-time-edit_select"}
              .icon-chevron-down
                = fa_icon("chevron-down")
              .select-box-character
                月
            .date-send-btn
              = f.submit "確認", class: "send-btn", id: "fix-time-edit_date-send-btn"

    .mytimes-show-wrapper__contents
      = form_with(url: fix_time_path, method: :patch, local: true, class: "mytimes-show-wrapper__contents__form") do |f|
        = f.hidden_field :year, value: "#{@year}"
        = f.hidden_field :month, value: "#{@month}"
        = f.hidden_field :user_id, value: "#{@user.id}"

        .mytimes-show-wrapper-contents-table-width
        .mytimes-show-wrapper__contents__table
          %table
            = render 'mytimes/tr_title'
            - @attendances.each do |attendance|
              -if attendance[0] == "holiday"
                = fields_for "newAttendances[]", attendance[2] do |n|
                  %tr
                    %td= set_date(attendance[1])
                    %td 休
                    %td{class: "td-form-input"}= n.time_field :going_to_work, class: "form-value-input"
                    %td{class: "td-form-input"}= n.time_field :leave_work, class: "form-value-input"
                    %td
                  = n.hidden_field :date, value: "#{set_day(attendance[1])}"
              -else
                = fields_for "editAttendances[]", attendance do |e|
                  %tr
                    %td= set_date(attendance.going_to_work)
                    %td
                    %td{class: "td-form-input"}= e.time_field :going_to_work, value: "#{set_time(attendance.going_to_work)}", class: "form-value-input"
                    -if attendance.leave_work
                      %td{class: "td-form-input"}= e.time_field :leave_work, value: "#{set_time(attendance.leave_work)}", class: "form-value-input"
                      %td= set_working_hours(attendance.going_to_work, attendance.leave_work)
                    -else
                      %td{class: "td-form-input"}= e.time_field :leave_work, class: "form-value-input"
                      %td
                  = e.hidden_field :id, value: "#{attendance.id}"
        .mytimes-show-wrapper__contents__send-btn
          .mytimes-show-wrapper__contents__send-btn__top
            = f.submit "修正する", class: "fix-attendance-btn"
          .mytimes-show-wrapper__contents__send-btn__bottom
            = f.submit "修正する", class: "fix-attendance-btn"

  .fix-wrapper__footer

app/views/fix_time/index.html.haml
.fix-wrapper
  .mytimes-show-wrapper
    = render partial: 'mytimes/title_header', locals: { page_title: "勤怠確認と修正" }

    .mytimes-show-wrapper__header
      = form_with(url: edit_fix_time_path(current_user.id), method: :get, local: true, class: "date-form-area", id: "date-and-name-form-area") do |f|
        .header-form
          .header-form__name
            = collection_select(:user, :name_select, User.all, :id, :name, selected: current_user.id)
            .icon-chevron-down
              = fa_icon("chevron-down") 
          .header-form__date
            = render 'mytimes/header_form_date_contents'
            .date-send-btn
              = f.submit "選択", class: "send-btn"
    .mytimes-show-wrapper__footer