config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  root "home#index"
  resources :home, only: [:index] # ホーム画面（各ページへのリンクが存在）
  resources :emboss, only: [:index, :create] # 勤怠打刻
  resources :mytimes, only: [:index, :show] # 自分の勤怠を確認
  resources :fix_time, only: [:index, :edit, :update] # 勤怠修正
  resources :change_auth, only: [:index, :update] # 権限設定
end

app/controllers/change_auth_controller.rb
class ChangeAuthController < ApplicationController
  # 権限設定に関するコントローラー

  before_action :move_to_Log_in
  before_action :check_authority_Stop_other_than_admin

  def index
    ids = User.joins(:authority).ids
    odd_records = User.where.not(id: ids)
    odd_records.each do |record|
      auth = record.build_authority(auth: 0)
      auth.save
    end
    @users = User.all.includes(:authority)
  end

  def update
    value = params.require(:value)
    user_id = params.require(:user_id)
    user = User.find(user_id)
    @result = user.authority.update(auth: value)
  end
end

app/views/change_auth/index.html.haml
.fix-wrapper
  .mytimes-show-wrapper
    = render partial: 'mytimes/title_header', locals: { page_title: "権限設定" }

    = form_with(url: change_auth_path(current_user.id), method: :patch, id: "change-auth_index_form") do |f|
      .change-auth-contents
        .change-auth-contents__member-area
          - @users.each do |user|
            .change-auth-contents__member-area__name-area
              .change-auth-contents__member-area__name-area__name
                = user.name
              .change-auth-contents__member-area__name-area__btn
                = f.select :authority, Authority.auths_i18n.keys.map{|k| [Authority.auths_i18n[k], k]}, {selected: user.authority.auth}, {class: "change-auth_index_select-auth", data: {id: "#{user.id}"}}
                .icon-chevron-down
                  = fa_icon("chevron-down")